class BluePrint {
  private static element: HTMLDivElement;
  private static ELEMENT_ID: string = 'blueprint-autogenerated-layer';

  public static insert(url: string, width: number, height: number) {
    if (!url) {
      throw new Error("specify image url");
    }
    if (this.element) {
      this.updateBackgroundUrl(url);
    } else {
      this.insertImage(url);
    }
    this.element.style.width  = width  + 'px';
    this.element.style.height = height + 'px';
  }

  public static setOpacity(opacity: string) {
    this.assertElement();
    this.element.style.opacity = opacity;
  }

  public static setOffset(_top: string, left: string) {
    this.assertElement();
    this.element.style.top  = _top;
    this.element.style.left = left;
  }

  public static show() {
    this.element.style.visibility = "visible";
  }

  public static hide() {
    this.element.style.visibility = "hidden";
  }

  private static insertImage(url: string) {
    this.element = document.createElement('div');
    this.updateBackgroundUrl(url);
    this.setBaseStyle(BluePrint.element);
    document.body.appendChild(this.element);
  }

  private static updateBackgroundUrl(url: string) {
    this.element.style.backgroundImage = 'url(' + url + ')'
  }

  private static setBaseStyle(img: HTMLDivElement) {
    img.style.position = "absolute";
    img.style.top      = "0";
    img.style.left     = "0";
    img.style.zIndex   = "999";
    img.style.opacity  = "0.5";
  }

  private static assertElement() {
    if (!this.element) {
      throw new Error("call insertImage(url) at first");
    }
  }

}

